name: shelf_learn
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: qyang <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  # args: ^1.4.2
  shelf: ^0.7.2
  shelf_static: ^0.2.8
  sqljocky5: ^2.2.1
  test: ^1.5.3
  random_string: ^0.0.2


dev_dependencies:
  pedantic: ^1.0.0
